services:
 postgres:
   image: postgres:latest
   environment:
     POSTGRES_DB: ${POSTGRES_DB}
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
   ports:
     - "${POSTGRES_PORT}:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data

 qdrant:
   image: qdrant/qdrant:latest
   ports:
     - "${QDRANT_HTTP_PORT}:6333"  # REST API
     - "${QDRANT_GRPC_PORT}:6334"  # gRPC API  
   volumes:
     - qdrant_data:/qdrant/storage
   environment:
     QDRANT__SERVICE__ENABLE_CORS: true
     QDRANT__SERVICE__API_KEY: ${QDRANT_API_KEY}
     QDRANT__LOG_LEVEL: INFO

 dragonfly:
   image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
   ports:
     - "${REDIS_PORT}:6379"
   command: dragonfly --requirepass=${REDIS_PASSWORD}
   volumes:
     - dragonfly_data:/data

volumes:
 postgres_data:
 qdrant_data:
 dragonfly_data: