"""partition files

Revision ID: 05394cce4945
Revises: 344c303f7313
Create Date: 2025-07-16 20:37:17.287613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05394cce4945'
down_revision: Union[str, Sequence[str], None] = '344c303f7313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_files_files_bucket_name'), table_name='files')
    op.create_index(op.f('idx_files_files_bucket_name'), 'files', ['bucket_name', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_files_files_bucket_name'), table_name='files')
    op.create_index(op.f('idx_files_files_bucket_name'), 'files', ['bucket_name'], unique=False)
    # ### end Alembic commands ###
