"""small update

Revision ID: 1516392953b5
Revises: e5c80b22a884
Create Date: 2025-07-16 14:32:32.858637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1516392953b5'
down_revision: Union[str, Sequence[str], None] = 'e5c80b22a884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_files_bucket_name'), table_name='files')
    op.drop_index(op.f('idx_files_bucket_status'), table_name='files')
    op.drop_index(op.f('idx_files_object_key'), table_name='files')
    op.drop_index(op.f('idx_files_status'), table_name='files')
    op.create_index(op.f('idx_files_files_bucket_name'), 'files', ['bucket_name'], unique=False)
    op.create_index(op.f('idx_files_files_object_key'), 'files', ['object_key'], unique=False)
    op.create_index(op.f('idx_files_files_status'), 'files', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_files_files_status'), table_name='files')
    op.drop_index(op.f('idx_files_files_object_key'), table_name='files')
    op.drop_index(op.f('idx_files_files_bucket_name'), table_name='files')
    op.create_index(op.f('idx_files_status'), 'files', ['status'], unique=False)
    op.create_index(op.f('idx_files_object_key'), 'files', ['object_key'], unique=False)
    op.create_index(op.f('idx_files_bucket_status'), 'files', ['bucket_name', 'status'], unique=False)
    op.create_index(op.f('idx_files_bucket_name'), 'files', ['bucket_name'], unique=False)
    # ### end Alembic commands ###
