"""small update

Revision ID: 344c303f7313
Revises: 1516392953b5
Create Date: 2025-07-16 15:50:35.345291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '344c303f7313'
down_revision: Union[str, Sequence[str], None] = '1516392953b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('name', sa.String(), nullable=False, server_default='Untitled'))
    op.add_column('files', sa.Column('name', sa.String(length=256), nullable=True))
    
    # Copy data from file_name to name
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE files SET name = file_name WHERE name IS NULL"))
    
    # Now make the name column NOT NULL
    op.alter_column('files', 'name', nullable=False)
    
    # Finally, drop the old file_name column
    op.drop_column('files', 'file_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_name', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_column('files', 'name')
    op.drop_column('collections', 'name')
    # ### end Alembic commands ###
