"""partition files

Revision ID: 45216bd2a713
Revises: 05394cce4945
Create Date: 2025-07-16 20:39:05.457324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45216bd2a713'
down_revision: Union[str, Sequence[str], None] = '05394cce4945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partition_files',
    sa.Column('partition_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_partition_files_file_id')),
    sa.ForeignKeyConstraint(['partition_id'], ['partitions.id'], name=op.f('fk_partition_files_partition_id')),
    sa.PrimaryKeyConstraint('partition_id', 'file_id', name=op.f('pk_partition_files'))
    )
    op.create_index(op.f('idx_partition_files_partition_files_file_id'), 'partition_files', ['file_id'], unique=False)
    op.create_index(op.f('idx_partition_files_partition_files_partition_id'), 'partition_files', ['partition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_partition_files_partition_files_partition_id'), table_name='partition_files')
    op.drop_index(op.f('idx_partition_files_partition_files_file_id'), table_name='partition_files')
    op.drop_table('partition_files')
    # ### end Alembic commands ###
