"""current database state

Revision ID: 525d47ee5471
Revises: 
Create Date: 2025-07-08 21:28:49.242410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '525d47ee5471'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=256), nullable=False),
    sa.Column('mime_type', sa.String(length=32), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('bucket_name', sa.String(length=256), nullable=False),
    sa.Column('object_key', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_files_bucket_name', 'files', ['bucket_name'], unique=False)
    op.create_index('idx_files_bucket_status', 'files', ['bucket_name', 'status'], unique=False)
    op.create_index('idx_files_object_key', 'files', ['object_key'], unique=False)
    op.create_index('idx_files_status', 'files', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_files_status', table_name='files')
    op.drop_index('idx_files_object_key', table_name='files')
    op.drop_index('idx_files_bucket_status', table_name='files')
    op.drop_index('idx_files_bucket_name', table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
