"""fix status field type

Revision ID: 54a7ddabe5e2
Revises: 8de8bbe403e4
Create Date: 2025-07-12 15:00:55.383760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54a7ddabe5e2'
down_revision: Union[str, Sequence[str], None] = '8de8bbe403e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('embedding_model', sa.String(), nullable=False))
    op.alter_column('collections', 'status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.drop_column('collections', 'embeddingModel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('embeddingModel', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('collections', 'status',
               existing_type=sa.String(length=64),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    op.drop_column('collections', 'embedding_model')
    # ### end Alembic commands ###
