"""Initial setup test 2

Revision ID: 6369a84dbdf5
Revises: 3dd7b5148d3f
Create Date: 2025-07-05 11:04:39.839081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6369a84dbdf5'
down_revision: Union[str, Sequence[str], None] = '3dd7b5148d3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
