"""update collections table

Revision ID: 8de8bbe403e4
Revises: 525d47ee5471
Create Date: 2025-07-12 14:43:22.853908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8de8bbe403e4'
down_revision: Union[str, Sequence[str], None] = '525d47ee5471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('embeddingModel', sa.String(), nullable=False))
    op.add_column('collections', sa.Column('shard_number', sa.Integer(), nullable=False))
    op.add_column('collections', sa.Column('replication_factor', sa.Integer(), nullable=False))
    op.add_column('collections', sa.Column('status', sa.Boolean(), nullable=False))
    op.add_column('collections', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('collections', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('collections', 'hnsw_m',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('collections', 'hnsw_payload_m',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('files', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('files', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'updated_at')
    op.drop_column('files', 'created_at')
    op.alter_column('collections', 'hnsw_payload_m',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('collections', 'hnsw_m',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('collections', 'updated_at')
    op.drop_column('collections', 'created_at')
    op.drop_column('collections', 'status')
    op.drop_column('collections', 'replication_factor')
    op.drop_column('collections', 'shard_number')
    op.drop_column('collections', 'embeddingModel')
    # ### end Alembic commands ###
